### ISSUE TITLE
Create Docker based k6 builder library

### ISSUE THREAD

**Issue by pablochacin** [grafana/k6build#23]
`k6foundry` implements the local builder, `k6build` implements the build service client. A Docker-based builder library is needed, which implements k6 builder using the Docker runtime.

```[tasklist]
### Tasks
```

**Comment by pablochacin** [comment]
@szkiba given that k6foundry already implements the native builder, maybe the docker build library could be located there. WDYT?

**Comment by szkiba** [comment]
I think it would be better in a separate package (due to dependencies). If someone only wants a local builder, then the docker dependencies will not be built in.

**Comment by szkiba** [comment]
But it can be together initially and then separated if needed.

**Comment by pablochacin** [comment]
The dependencies is a good point. 

I was thinking more about having the same k6foundry interface, so from the perspective of k6build it is transparent which foundry we use (local golang toolchain or docker)
